apiVersion: v1
kind: Service
metadata:
  name: acceptor-nodeport
  namespace: instana-core
spec:
  ports:
    - name: http-service
      port: 8600
      nodePort: 30950
      protocol: TCP
  selector:
    application: instana
    component: acceptor
    group: service
  type: NodePort
